# Run rustfmt with this config (it should be picked up automatically).
version = "Two"
merge_derives = true
reorder_imports = true
unstable_features = true     # 使能 unstable 特性
## unstable features below ##
# 格式化注释代码块：Unstable
format_code_in_doc_comments = true
# 重新排序mod
reorder_modules = true
# 按照 crate 重新排序
imports_granularity = "Crate"
# 过长换行使用大括号
match_arm_blocks = true
# 数组换行
indent_style = "Block"
# 彩色输出：Unstable
color = "Auto"
