name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: |
        cargo build -r
        strip target/release/bot-rs
        sudo apt-get update
        sudo apt-get install -y upx
        upx -7 target/release/bot-rs
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: bot-rs
        path: target/release/bot-rs
